collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5225564
  brandStrength: 0.5081454
  lightness: 0.5
  brandColors:
    - '#000000'
    - '#FFFBFF'
    - '#FFE6FF'
    - '#FFD6FF'
    - '#141031'
  rhythmicContrast: 0.4699871
typography_spectrum: 0.6424958
layout_spectrum: 0.9172933
name: 'TheLoveVoiceMovement '
